# Generated by Django 4.2.5 on 2023-10-02 23:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('indice', models.IntegerField()),
                ('descricao', models.CharField(max_length=150)),
                ('problema', models.TextField(max_length=255)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ordemservico', to_field='numero')),
            ],
        ),
    ]
